[package]
name = "deft-app"
version = "0.1.0"
edition = "2021"

[dependencies]
deft = "0.1.5"

[build-dependencies]
deft-build = { version = "0.1.1" }

[features]
tray = ["deft/tray"]

[lib]
name = "deftapp"
path = "src/main.rs"
crate-type=["cdylib"]